revert to not use halcyon in travis

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,23 +1,52 @@
-# From https://robots.thoughtbot.com/building-haskell-projects-with-halcyon
-#
+# From https://github.com/hvr/multi-ghc-travis
 
-language: sh
+# NB: don't set `language: haskell` here
 
+# The following enables several GHC versions to be tested; often it's enough to test only against the last release in a major GHC version. Feel free to omit lines listings versions you don't need/want testing for.
 env:
-  global:
-  - secure: rEx6vAekoXA41qvUo8wrHmcWu8dokXaDvT8ndz2c76NJngct9LESXFQHAplPDhBdvfGVBB0+Tv/2hHJVEi/2LbhojIZ1AS382EsV9EJJo4Iuzmjsz+1nJ4w+RH4yDDKdORSDGc9nleOap/XKPhemkTaKUL8euCcxkavnG6CQ3JPqtV8bLgIx8p/TqxDSP9/3R49ghT1oiA2Fg7AFAJDG9m/yta7zYLWQ1CiV5F46tDqgUzSqTJu47RmUOhqzFXFJzbznXSlGe3o149lb9etXwQxvZbkTXexopSVo/Gr4qTGjG56hxSZCX9opWVLxLK8NHfo8U6NYO7F1OIkKb/+gy9VlcCIaDtpuy24choEtqYuMkz56SIXDuLx5st+55+b3OjS1+4Dr5dmZA1NEK0Ld2X3bkYIxSX+9PeixrNbdqHOsZMJi6xYQ0CRAo9yuR/2VhhVdbat2IxwVIEA8690IndpfQkORbsqRijpyITuI0tuxi/ToO0bPOupahXNGQWJiGsrS4Gdo6dR/XnPjJkhv/JxbPjMyM876aPqvLiT03HJYXVUhY8MfebTIcBudSDOmSvcv+ZtdVgYIEyZDZ2JnDwYVRC/dI0RC8WW/g/zk4USsNbnxDTZJ8PIv1lLXKOEXwZRjZlA/BKhAvCrr5dnXBlawx+rqpcRThwZte03SpXg=
-  - secure: rWIq8G2A23fUA7Z62U9yB2b+Z2p6Q/d/bEx+HIM/k4gkXRaYOWEflWC6zJMbKgMobIOLNkNCWr/1ucWNwUrLs9r4cEHpdKC7SS32JKzcWvegQz284wX7coQ8L4zhPqxQnA7hUA1c9ZlAagtZ2bfkxCjf4vlTl5Oza4NR1SrUmwAT7ZPI8RLe9sAHi0cDCXx6Li8IVNDfvqcStRDbnMA64Vz0uHeI5lJ7vtYTLJ1rZwSGGXSVne8y3DxmbTj6BZl2szBofTyJrIw5K7PoUcJUIQXgo0TOHE6roVJsYjBnnd9hIjrQq1viD/HCh02tXuMX8Tc29r3HbMfFZOT6pN/0hVmfN51AeP2BjukLGI95jDkFGg6F5h6RZ6XEEfFnpJl1KsCf9i9zrCrLkhQAmV6eH74zknnlik42Su8dlxxQbp9LioaNAmm8O1jGjXp2tjJbVCLH/MVqsybv6cKHp4POuEBMGnSGPkFvAGdalaHU8GCplTlY628RJf8RhC9Gy1rwanEjQXB0J4Hnc7WBqmuQdyPHicnbSbiYnTa4jgb/sdTLc5uAoGKvumUOjHdgEe+wEk/F6ZqMPjyQNYEoAR8lqao72NzwRCLo/zxfxW4TH4QQPe7LDBu5za9hAyZ57a7uTdU6cqYHcDlZ+DU+jNuhjxa7AevHrglTLya6oTdNOsA=
-  - secure: WwHvn9Zsl19u13OZOCxNLYeSWOhP8UWVCkrPlqdIjQr4pm+fNxIir01BrT8OW09Fa0f9vJzQk0bJrWI37DrK3BM4Ae4LXJg5Kfng99Bbd08VLZdlLEiiKdtVwR2olD8Zljm7KdyNt3anZoTikRrM25vcP4vj50uRCVvZUNs61zvQRJDOaCDICM66PulHSq/TXtsaVn0lwUAgIx5CN20UauzY29QDbr2gDpBwVZAa4LzYkt7nsz53ythPmSc9KxW8gEje7I8ghKXGzkc+hjTNkNb2O3ZjfHEyKUuet56LxfpkBjJcPWXHBrB1lec9mFDXMJxzmz15SxOe9EzXazx278dpYbc8dwQzgLX3tKeKv0B0j9xRd+CtaBA0JaO8bss6ORGrflu28IeYFXvT2dQhaXpJVnGsiuytWdGFbu7/5UmmrvwwYLZzGCIrLEeYnYPnsQoUeemo+jlTTAMpe7xK1hlwierQNKXRmeeiIDxXsBAJOolppbpLTNejb/h+YeqqI4g+gKtjA3RsvreMxeJiomYCgChjAkfxxANU6i5Ny5itt8JeUsxUB/DMtqWvQdmG6bqU6bOUA+TTJ5CD5Io7vRXSOt1FBBDQcN1+Qne8Nqu4HbR7gP0LTpRNZdI4Te9ZH54p/RmGMbkIqNvTkzgWIpJ/Rgu4KQDK1U9wckTuIC0=
+ - CABALVER=1.18 GHCVER=7.8.4
+ - CABALVER=1.22 GHCVER=7.10.1
+ - CABALVER=head GHCVER=head   # see section about GHC HEAD snapshots
 
+matrix:
+  allow_failures:
+   - env: CABALVER=head GHCVER=head
+
+# Note: the distinction between `before_install` and `install` is not important.
 before_install:
-- sudo mkdir -p /app
-- sudo chown $USER /app
-- git clone https://github.com/mietek/halcyon.git /app/halcyon
+ - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
+ - travis_retry sudo apt-get update
+ - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER # see note about happy/alex
+ - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
+ - |
+   if [ $GHCVER = "head" ] || [ ${GHCVER%.*} = "7.8" ] || [ ${GHCVER%.*} = "7.10" ]; then
+     travis_retry sudo apt-get install happy-1.19.4 alex-3.1.3
+     export PATH=/opt/alex/3.1.3/bin:/opt/happy/1.19.4/bin:$PATH
+   else
+     travis_retry sudo apt-get install happy alex
+   fi
 
 install:
-- "/app/halcyon/halcyon build"
-- "/app/halcyon/halcyon paths > halcyon-env"
-- ln -sf /app/sandbox/cabal.sandbox.config cabal.sandbox.config
+ - cabal --version
+ - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
+ - travis_retry cabal update
+ - cabal install --only-dependencies --enable-tests --enable-benchmarks
 
+# Here starts the actual work to be performed for the package under test; any command which exits with a non-zero exit code causes the build to fail.
 script:
-- source halcyon-env && cabal configure --enable-tests && cabal test
+ - if [ -f configure.ac ]; then autoreconf -i; fi
+ - cabal configure --enable-tests --enable-benchmarks -v2  # -v2 provides useful information for debugging
+ - cabal build   # this builds all libraries and executables (including tests/benchmarks)
+ - cabal test
+ - cabal check
+ - cabal sdist   # tests that a source-distribution can be generated
+
+# The following scriptlet checks that the resulting source distribution can be built & installed
+ - export SRC_TGZ=$(cabal info . | awk '{print $2 ".tar.gz";exit}') ;
+   cd dist/;
+   if [ -f "$SRC_TGZ" ]; then
+      cabal install --force-reinstalls "$SRC_TGZ";
+   else
+      echo "expected '$SRC_TGZ' not found";
+      exit 1;
+   fi
